from framework.request.request import request_all_data
from framework.request.fire_image_v import get_fire_image_v
from framework.request.vad_frames_v import get_vad_frames_v
from framework.request.weather_image_v import get_weather_image_v
